name: Multi Environment CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'dev'
    
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use environment variables
        env:
          TEST: ${{ vars.TEST }}
          SOPS_AGE_KEY: ${{ secrets.TEST }}
        run: |
          echo "Deploying to $ENVIRONMENT environment..."
          echo "TEST=$TEST"
