name: Multi Environment CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  TEST: ${{ vars.TEST }}
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'pro' #dev
    
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use environment variables
        run: |
          echo "Deploying to $ENVIRONMENT environment..."
          echo "variables TEST=$TEST"
          echo "secrtes SOPS_AGE_KEY=$SOPS_AGE_KEY"
