name: Multi Environment CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'pro'
    
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use environment variables
        env:
          SOPS_AGE_KEY: ${{ variables.SOPS_AGE_KEY }}
        run: |
          echo "Deploying to $ENVIRONMENT environment..."
          echo "SOPS_AGE_KEY=$SOPS_AGE_KEY"
